export const UPDATE_ART = "UPDATE_ART";
export const SET_CURRENT_DETAIL = "SET_CURRENT_DETAIL";
export const SET_CURRENT_COLLECTION = "SET_CURRENT_PAGE";
export const LOADING = "LOADING";

export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
